gesdinet_jwt_refresh_token:
    firewall: token-refresh
    user_provider: fos_user.user_provider.username_email
    token_parameter_name: refreshToken
    single_use: true
    ttl: "%jwt_refresh_token_ttl%"